name: build
on:
  - push

env:
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  release:
    # needs: test
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/master'
    name: npm upload
    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"

      - name: cache
        uses: actions/cache@v2.1.1
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: upload
        run: |
          git submodule update --init --recursive
          make build
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish || true
          unlink katex/README.md && cp README.md katex/README.md
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > katex/.npmrc
          cd katex && npm publish || true
